#!/usr/bin/env python3

import argparse
import json
import os
import re
import sys

from junit_xml import TestSuite, TestCase


parser = argparse.ArgumentParser()
parser.add_argument("classname")
parser.add_argument("koladir")
parser.add_argument("outputxml")
args = parser.parse_args()

with open(os.path.join(args.koladir, "reports/report.json")) as f:
    report = json.load(f)


# https://stackoverflow.com/a/14693789
def strip_ansi(text):
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    return ansi_escape.sub('', text)


# In a {kola_outputdir}/{testname}/ dir, there can be multiple directories; one
# per host that was brought up. e.g. the Tang test brings up a Tang server in a
# separate host. We can only report one host, so we choose the one whose dir
# was created most recently since that's more likely to be the one with the
# error.
def get_most_recent_host_dir(parent_dir):
    # special case for testiso tests, where there's no nested dir per host
    if os.path.exists(os.path.join(parent_dir, "console.txt")):
        return parent_dir

    most_recent = None
    most_recent_ts = 0
    for dirent in os.listdir(parent_dir):
        path = os.path.join(parent_dir, dirent)
        if not os.path.isdir(path):
            continue
        ts = os.path.getctime(path)
        if ts > most_recent_ts:
            most_recent = path
            most_recent_ts = ts
    if most_recent is None:
        raise Exception(f"no directory found in {parent_dir}")
    return most_recent


test_cases = []
for test in report['tests']:
    if '/' in test['name']:
        # a subtest; we don't normally report them, except bucketed tests since
        # they're really full tests of their own
        main_test, subtest = test['name'].split('/')
        if not main_test.startswith('non-exclusive-test-bucket-'):
            continue
        dirname = main_test
        test['name'] = subtest
    else:
        dirname = test['name']

    console_txt = None
    journal_txt = None
    ext_test_out = None

    # we only add output/console/journal for failing tests
    if test['result'] != 'PASS':
        host_dir = get_most_recent_host_dir(f"{args.koladir}/{dirname}")
        console_fn = os.path.join(host_dir, "console.txt")
        if os.path.isfile(console_fn):
            with open(console_fn, encoding='utf-8') as f:
                console_txt = strip_ansi(f.read())
        journal_fn = os.path.join(host_dir, "journal.txt")
        if os.path.isfile(journal_fn):
            with open(journal_fn, encoding='utf-8') as f:
                journal_txt = f.read()
        if test['name'].startswith('ext.'):
            ext_test_out_fn = os.path.join(host_dir, f"{test['name']}.txt")
            if os.path.isfile(ext_test_out_fn):
                with open(ext_test_out_fn, encoding='utf-8') as f:
                    ext_test_out = f.read()

    # for external tests; we consider the kola-runext.service output its output
    if ext_test_out is not None:
        test['output'] = ext_test_out
    test['output'] = strip_ansi(test['output'])

    tc = TestCase(test['name'], args.classname + ".tests",
                  test['duration'] / 10**9,
                  stdout=console_txt, stderr=journal_txt)

    if test["result"] == 'FAIL':
        tc.add_failure_info(output=test["output"])

    elif test["result"] == 'SKIP':
        tc.add_skipped_info(output=test["output"])

    test_cases.append(tc)

ts = TestSuite(args.classname, test_cases)
if args.outputxml == '-':
    TestSuite.to_file(sys.stdout, [ts])
else:
    with open(args.outputxml, "w", encoding='utf-8') as f:
        TestSuite.to_file(f, [ts])
